version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    environment:
      NODE_ENV: production
      NAME_API: API
      CORS_URL: '*'
      PREFIX_API: /api/v1.0
      MONGO_URI: mongodb://root:root@mongo:27017
      MONGO_DATABASE: backend-clean
      EMAIL_DOMAIN: dominio.com.co
      RIJNDAEL_KEY: key
      SEED: sdfgsdffgsf
      EXPIRES_IN: 15
      PORT: 9000
    container_name: app
    restart: unless-stopped
    ports:
      - 5000:9000
    links:
      - mongo

  mongo:
    container_name: backend-clean-db
    image: mongo:5.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
